Search.appendIndex(
    [
                {
            "fqsen": "\\Router",
            "name": "Router",
            "summary": "Router\u0020class\u0020\u002D\u0020Main\u0020application\u0020router\nHandles\u0020URL\u0020routing\u0020and\u0020controller\u0020dispatching\u0020with\u0020namespaces",
            "url": "classes/Router.html"
        },                {
            "fqsen": "\\Router\u003A\u003Aroute\u0028\u0029",
            "name": "route",
            "summary": "Route\u0020the\u0020request\u0020to\u0020the\u0020appropriate\u0020controller",
            "url": "classes/Router.html#method_route"
        },                {
            "fqsen": "\\Router\u003A\u003AloadController\u0028\u0029",
            "name": "loadController",
            "summary": "Load\u0020and\u0020execute\u0020controller\u0020method\u0020\u0028legacy\u0020\u002D\u0020old\u0020controllers\u0029",
            "url": "classes/Router.html#method_loadController"
        },                {
            "fqsen": "\\Router\u003A\u003AloadNamespacedController\u0028\u0029",
            "name": "loadNamespacedController",
            "summary": "Load\u0020and\u0020execute\u0020namespaced\u0020controller\u0020method\u0020\u0028new\u0020MVC\u0020structure\u0029",
            "url": "classes/Router.html#method_loadNamespacedController"
        },                {
            "fqsen": "\\Router\u003A\u003AloadView\u0028\u0029",
            "name": "loadView",
            "summary": "Load\u0020a\u0020static\u0020view\u0020directly",
            "url": "classes/Router.html#method_loadView"
        },                {
            "fqsen": "\\Controllers\\Analysis\\UploadController",
            "name": "UploadController",
            "summary": "Contr\u00F4leur\u0020pour\u0020l\u0027upload\u0020des\u0020donn\u00E9es\u0020de\u0020programmes\u0020\u00E9tudiants",
            "url": "classes/Controllers-Analysis-UploadController.html"
        },                {
            "fqsen": "\\Controllers\\Analysis\\UploadController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Controllers-Analysis-UploadController.html#method___construct"
        },                {
            "fqsen": "\\Controllers\\Analysis\\UploadController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "Affiche\u0020la\u0020page\u0020d\u0027upload",
            "url": "classes/Controllers-Analysis-UploadController.html#method_index"
        },                {
            "fqsen": "\\Controllers\\Analysis\\UploadController\u003A\u003Aupload\u0028\u0029",
            "name": "upload",
            "summary": "Traite\u0020l\u0027upload\u0020du\u0020fichier\u0020JSON",
            "url": "classes/Controllers-Analysis-UploadController.html#method_upload"
        },                {
            "fqsen": "\\Controllers\\Analysis\\UploadController\u003A\u003A\u0024code2vecService",
            "name": "code2vecService",
            "summary": "",
            "url": "classes/Controllers-Analysis-UploadController.html#property_code2vecService"
        },                {
            "fqsen": "\\Controllers\\Analysis\\VectorController",
            "name": "VectorController",
            "summary": "Contr\u00F4leur\u0020pour\u0020la\u0020g\u00E9n\u00E9ration\u0020et\u0020la\u0020gestion\u0020des\u0020vecteurs",
            "url": "classes/Controllers-Analysis-VectorController.html"
        },                {
            "fqsen": "\\Controllers\\Analysis\\VectorController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Controllers-Analysis-VectorController.html#method___construct"
        },                {
            "fqsen": "\\Controllers\\Analysis\\VectorController\u003A\u003Agenerate\u0028\u0029",
            "name": "generate",
            "summary": "Lance\u0020la\u0020g\u00E9n\u00E9ration\u0020de\u0020vecteurs\u0020pour\u0020un\u0020dataset",
            "url": "classes/Controllers-Analysis-VectorController.html#method_generate"
        },                {
            "fqsen": "\\Controllers\\Analysis\\VectorController\u003A\u003Aprocessing\u0028\u0029",
            "name": "processing",
            "summary": "Page\u0020de\u0020traitement\u0020avec\u0020barre\u0020de\u0020progression",
            "url": "classes/Controllers-Analysis-VectorController.html#method_processing"
        },                {
            "fqsen": "\\Controllers\\Analysis\\VectorController\u003A\u003Astatus\u0028\u0029",
            "name": "status",
            "summary": "API\u0020pour\u0020v\u00E9rifier\u0020le\u0020statut\u0020du\u0020traitement\u0020\u0028AJAX\u0029",
            "url": "classes/Controllers-Analysis-VectorController.html#method_status"
        },                {
            "fqsen": "\\Controllers\\Analysis\\VectorController\u003A\u003AgetVectors\u0028\u0029",
            "name": "getVectors",
            "summary": "R\u00E9cup\u00E8re\u0020les\u0020vecteurs\u0020g\u00E9n\u00E9r\u00E9s",
            "url": "classes/Controllers-Analysis-VectorController.html#method_getVectors"
        },                {
            "fqsen": "\\Controllers\\Analysis\\VectorController\u003A\u003A\u0024code2vecService",
            "name": "code2vecService",
            "summary": "",
            "url": "classes/Controllers-Analysis-VectorController.html#property_code2vecService"
        },                {
            "fqsen": "\\Controllers\\Analysis\\VectorController\u003A\u003A\u0024datasetModel",
            "name": "datasetModel",
            "summary": "",
            "url": "classes/Controllers-Analysis-VectorController.html#property_datasetModel"
        },                {
            "fqsen": "\\Controllers\\Analysis\\VisualizationController",
            "name": "VisualizationController",
            "summary": "Contr\u00F4leur\u0020pour\u0020la\u0020visualisation\u0020des\u0020donn\u00E9es\u0020avec\u0020D3.js",
            "url": "classes/Controllers-Analysis-VisualizationController.html"
        },                {
            "fqsen": "\\Controllers\\Analysis\\VisualizationController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Controllers-Analysis-VisualizationController.html#method___construct"
        },                {
            "fqsen": "\\Controllers\\Analysis\\VisualizationController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "Affiche\u0020la\u0020page\u0020de\u0020visualisation",
            "url": "classes/Controllers-Analysis-VisualizationController.html#method_index"
        },                {
            "fqsen": "\\Controllers\\Analysis\\VisualizationController\u003A\u003AgetData\u0028\u0029",
            "name": "getData",
            "summary": "API\u0020pour\u0020r\u00E9cup\u00E9rer\u0020les\u0020donn\u00E9es\u0020format\u00E9es\u0020pour\u0020D3.js",
            "url": "classes/Controllers-Analysis-VisualizationController.html#method_getData"
        },                {
            "fqsen": "\\Controllers\\Analysis\\VisualizationController\u003A\u003A\u0024datasetModel",
            "name": "datasetModel",
            "summary": "",
            "url": "classes/Controllers-Analysis-VisualizationController.html#property_datasetModel"
        },                {
            "fqsen": "\\Controllers\\Auth\\AuthController",
            "name": "AuthController",
            "summary": "AuthController\u0020\u002D\u0020Authentication\u0020service\u0020with\u0020CRUD\u0020operations\nHandles\u0020user\u0020registration,\u0020login,\u0020and\u0020password\u0020management",
            "url": "classes/Controllers-Auth-AuthController.html"
        },                {
            "fqsen": "\\Controllers\\Auth\\AuthController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Controllers-Auth-AuthController.html#method___construct"
        },                {
            "fqsen": "\\Controllers\\Auth\\AuthController\u003A\u003Aregister\u0028\u0029",
            "name": "register",
            "summary": "CREATE\u0020\u002D\u0020Register\u0020a\u0020new\u0020user",
            "url": "classes/Controllers-Auth-AuthController.html#method_register"
        },                {
            "fqsen": "\\Controllers\\Auth\\AuthController\u003A\u003AvalidateCode\u0028\u0029",
            "name": "validateCode",
            "summary": "CREATE\u0020\u002D\u0020Validate\u0020verification\u0020code\u0020and\u0020create\u0020user\u0020account",
            "url": "classes/Controllers-Auth-AuthController.html#method_validateCode"
        },                {
            "fqsen": "\\Controllers\\Auth\\AuthController\u003A\u003Alogin\u0028\u0029",
            "name": "login",
            "summary": "READ\u0020\u002D\u0020Login\u0020user",
            "url": "classes/Controllers-Auth-AuthController.html#method_login"
        },                {
            "fqsen": "\\Controllers\\Auth\\AuthController\u003A\u003AresendCode\u0028\u0029",
            "name": "resendCode",
            "summary": "UPDATE\u0020\u002D\u0020Resend\u0020verification\u0020code",
            "url": "classes/Controllers-Auth-AuthController.html#method_resendCode"
        },                {
            "fqsen": "\\Controllers\\Auth\\AuthController\u003A\u003ArequestPasswordReset\u0028\u0029",
            "name": "requestPasswordReset",
            "summary": "UPDATE\u0020\u002D\u0020Request\u0020password\u0020reset",
            "url": "classes/Controllers-Auth-AuthController.html#method_requestPasswordReset"
        },                {
            "fqsen": "\\Controllers\\Auth\\AuthController\u003A\u003AresetPassword\u0028\u0029",
            "name": "resetPassword",
            "summary": "UPDATE\u0020\u002D\u0020Reset\u0020password\u0020with\u0020token",
            "url": "classes/Controllers-Auth-AuthController.html#method_resetPassword"
        },                {
            "fqsen": "\\Controllers\\Auth\\AuthController\u003A\u003AcreateSession\u0028\u0029",
            "name": "createSession",
            "summary": "Create\u0020user\u0020session",
            "url": "classes/Controllers-Auth-AuthController.html#method_createSession"
        },                {
            "fqsen": "\\Controllers\\Auth\\AuthController\u003A\u003A\u0024userModel",
            "name": "userModel",
            "summary": "",
            "url": "classes/Controllers-Auth-AuthController.html#property_userModel"
        },                {
            "fqsen": "\\Controllers\\Auth\\AuthController\u003A\u003A\u0024pendingRegistrationModel",
            "name": "pendingRegistrationModel",
            "summary": "",
            "url": "classes/Controllers-Auth-AuthController.html#property_pendingRegistrationModel"
        },                {
            "fqsen": "\\Controllers\\Auth\\AuthController\u003A\u003A\u0024emailService",
            "name": "emailService",
            "summary": "",
            "url": "classes/Controllers-Auth-AuthController.html#property_emailService"
        },                {
            "fqsen": "\\Controllers\\Auth\\EmailVerificationController",
            "name": "EmailVerificationController",
            "summary": "EmailVerificationController\u0020\u002D\u0020Handles\u0020email\u0020verification",
            "url": "classes/Controllers-Auth-EmailVerificationController.html"
        },                {
            "fqsen": "\\Controllers\\Auth\\EmailVerificationController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Controllers-Auth-EmailVerificationController.html#method___construct"
        },                {
            "fqsen": "\\Controllers\\Auth\\EmailVerificationController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "Show\u0020email\u0020verification\u0020page",
            "url": "classes/Controllers-Auth-EmailVerificationController.html#method_index"
        },                {
            "fqsen": "\\Controllers\\Auth\\EmailVerificationController\u003A\u003Averify\u0028\u0029",
            "name": "verify",
            "summary": "Verify\u0020email\u0020code",
            "url": "classes/Controllers-Auth-EmailVerificationController.html#method_verify"
        },                {
            "fqsen": "\\Controllers\\Auth\\EmailVerificationController\u003A\u003AresendCode\u0028\u0029",
            "name": "resendCode",
            "summary": "Resend\u0020verification\u0020code",
            "url": "classes/Controllers-Auth-EmailVerificationController.html#method_resendCode"
        },                {
            "fqsen": "\\Controllers\\Auth\\EmailVerificationController\u003A\u003AgetErrorMessage\u0028\u0029",
            "name": "getErrorMessage",
            "summary": "Get\u0020error\u0020message\u0020from\u0020error\u0020code",
            "url": "classes/Controllers-Auth-EmailVerificationController.html#method_getErrorMessage"
        },                {
            "fqsen": "\\Controllers\\Auth\\EmailVerificationController\u003A\u003AgetSuccessMessage\u0028\u0029",
            "name": "getSuccessMessage",
            "summary": "Get\u0020success\u0020message\u0020from\u0020success\u0020code",
            "url": "classes/Controllers-Auth-EmailVerificationController.html#method_getSuccessMessage"
        },                {
            "fqsen": "\\Controllers\\Auth\\EmailVerificationController\u003A\u003A\u0024authController",
            "name": "authController",
            "summary": "",
            "url": "classes/Controllers-Auth-EmailVerificationController.html#property_authController"
        },                {
            "fqsen": "\\Controllers\\Auth\\LoginController",
            "name": "LoginController",
            "summary": "LoginController\u0020\u002D\u0020Handles\u0020login\u0020display\u0020and\u0020authentication",
            "url": "classes/Controllers-Auth-LoginController.html"
        },                {
            "fqsen": "\\Controllers\\Auth\\LoginController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Controllers-Auth-LoginController.html#method___construct"
        },                {
            "fqsen": "\\Controllers\\Auth\\LoginController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "Show\u0020login\u0020page",
            "url": "classes/Controllers-Auth-LoginController.html#method_index"
        },                {
            "fqsen": "\\Controllers\\Auth\\LoginController\u003A\u003Aauthenticate\u0028\u0029",
            "name": "authenticate",
            "summary": "Process\u0020login\u0020form",
            "url": "classes/Controllers-Auth-LoginController.html#method_authenticate"
        },                {
            "fqsen": "\\Controllers\\Auth\\LoginController\u003A\u003AgetErrorMessage\u0028\u0029",
            "name": "getErrorMessage",
            "summary": "Get\u0020error\u0020message\u0020from\u0020error\u0020code",
            "url": "classes/Controllers-Auth-LoginController.html#method_getErrorMessage"
        },                {
            "fqsen": "\\Controllers\\Auth\\LoginController\u003A\u003AgetSuccessMessage\u0028\u0029",
            "name": "getSuccessMessage",
            "summary": "Get\u0020success\u0020message\u0020from\u0020success\u0020code",
            "url": "classes/Controllers-Auth-LoginController.html#method_getSuccessMessage"
        },                {
            "fqsen": "\\Controllers\\Auth\\LoginController\u003A\u003A\u0024authController",
            "name": "authController",
            "summary": "",
            "url": "classes/Controllers-Auth-LoginController.html#property_authController"
        },                {
            "fqsen": "\\Controllers\\Auth\\LogoutController",
            "name": "LogoutController",
            "summary": "LogoutController\u0020\u002D\u0020Handles\u0020user\u0020logout",
            "url": "classes/Controllers-Auth-LogoutController.html"
        },                {
            "fqsen": "\\Controllers\\Auth\\LogoutController\u003A\u003Alogout\u0028\u0029",
            "name": "logout",
            "summary": "Logout\u0020user\u0020and\u0020destroy\u0020session",
            "url": "classes/Controllers-Auth-LogoutController.html#method_logout"
        },                {
            "fqsen": "\\Controllers\\Auth\\PasswordResetController",
            "name": "PasswordResetController",
            "summary": "PasswordResetController\u0020\u002D\u0020Handles\u0020password\u0020reset\u0020functionality",
            "url": "classes/Controllers-Auth-PasswordResetController.html"
        },                {
            "fqsen": "\\Controllers\\Auth\\PasswordResetController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Controllers-Auth-PasswordResetController.html#method___construct"
        },                {
            "fqsen": "\\Controllers\\Auth\\PasswordResetController\u003A\u003AforgotPassword\u0028\u0029",
            "name": "forgotPassword",
            "summary": "Show\u0020forgot\u0020password\u0020page",
            "url": "classes/Controllers-Auth-PasswordResetController.html#method_forgotPassword"
        },                {
            "fqsen": "\\Controllers\\Auth\\PasswordResetController\u003A\u003ArequestReset\u0028\u0029",
            "name": "requestReset",
            "summary": "Request\u0020password\u0020reset",
            "url": "classes/Controllers-Auth-PasswordResetController.html#method_requestReset"
        },                {
            "fqsen": "\\Controllers\\Auth\\PasswordResetController\u003A\u003AshowResetForm\u0028\u0029",
            "name": "showResetForm",
            "summary": "Show\u0020reset\u0020password\u0020page\u0020with\u0020token",
            "url": "classes/Controllers-Auth-PasswordResetController.html#method_showResetForm"
        },                {
            "fqsen": "\\Controllers\\Auth\\PasswordResetController\u003A\u003AresetPassword\u0028\u0029",
            "name": "resetPassword",
            "summary": "Reset\u0020password\u0020with\u0020token",
            "url": "classes/Controllers-Auth-PasswordResetController.html#method_resetPassword"
        },                {
            "fqsen": "\\Controllers\\Auth\\PasswordResetController\u003A\u003AgetErrorMessage\u0028\u0029",
            "name": "getErrorMessage",
            "summary": "Get\u0020error\u0020message\u0020from\u0020error\u0020code",
            "url": "classes/Controllers-Auth-PasswordResetController.html#method_getErrorMessage"
        },                {
            "fqsen": "\\Controllers\\Auth\\PasswordResetController\u003A\u003A\u0024authController",
            "name": "authController",
            "summary": "",
            "url": "classes/Controllers-Auth-PasswordResetController.html#property_authController"
        },                {
            "fqsen": "\\Controllers\\Auth\\RegisterController",
            "name": "RegisterController",
            "summary": "RegisterController\u0020\u002D\u0020Handles\u0020user\u0020registration",
            "url": "classes/Controllers-Auth-RegisterController.html"
        },                {
            "fqsen": "\\Controllers\\Auth\\RegisterController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Controllers-Auth-RegisterController.html#method___construct"
        },                {
            "fqsen": "\\Controllers\\Auth\\RegisterController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "Show\u0020registration\u0020page",
            "url": "classes/Controllers-Auth-RegisterController.html#method_index"
        },                {
            "fqsen": "\\Controllers\\Auth\\RegisterController\u003A\u003Aregister\u0028\u0029",
            "name": "register",
            "summary": "Process\u0020registration\u0020form",
            "url": "classes/Controllers-Auth-RegisterController.html#method_register"
        },                {
            "fqsen": "\\Controllers\\Auth\\RegisterController\u003A\u003AgetErrorMessage\u0028\u0029",
            "name": "getErrorMessage",
            "summary": "Get\u0020error\u0020message\u0020from\u0020error\u0020code",
            "url": "classes/Controllers-Auth-RegisterController.html#method_getErrorMessage"
        },                {
            "fqsen": "\\Controllers\\Auth\\RegisterController\u003A\u003A\u0024authController",
            "name": "authController",
            "summary": "",
            "url": "classes/Controllers-Auth-RegisterController.html#property_authController"
        },                {
            "fqsen": "\\BaseController",
            "name": "BaseController",
            "summary": "BaseController\u0020\u002D\u0020Base\u0020controller\u0020class\u0020with\u0020common\u0020methods\nAll\u0020controllers\u0020should\u0020extend\u0020this\u0020class",
            "url": "classes/BaseController.html"
        },                {
            "fqsen": "\\BaseController\u003A\u003AloadView\u0028\u0029",
            "name": "loadView",
            "summary": "Load\u0020a\u0020view\u0020file\u0020with\u0020data",
            "url": "classes/BaseController.html#method_loadView"
        },                {
            "fqsen": "\\BaseController\u003A\u003Aredirect\u0028\u0029",
            "name": "redirect",
            "summary": "Redirect\u0020to\u0020a\u0020specific\u0020action",
            "url": "classes/BaseController.html#method_redirect"
        },                {
            "fqsen": "\\BaseController\u003A\u003AisAuthenticated\u0028\u0029",
            "name": "isAuthenticated",
            "summary": "Check\u0020if\u0020user\u0020is\u0020authenticated",
            "url": "classes/BaseController.html#method_isAuthenticated"
        },                {
            "fqsen": "\\BaseController\u003A\u003ArequireAuth\u0028\u0029",
            "name": "requireAuth",
            "summary": "Require\u0020authentication\u0020\u002D\u0020redirect\u0020to\u0020login\u0020if\u0020not\u0020authenticated",
            "url": "classes/BaseController.html#method_requireAuth"
        },                {
            "fqsen": "\\HomeController",
            "name": "HomeController",
            "summary": "HomeController\u0020\u002D\u0020Handles\u0020home\u0020page\u0020routing",
            "url": "classes/HomeController.html"
        },                {
            "fqsen": "\\HomeController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "Main\u0020index\u0020action\nRedirects\u0020authenticated\u0020users\u0020to\u0020dashboard,\u0020others\u0020to\u0020public\u0020home\u0020page",
            "url": "classes/HomeController.html#method_index"
        },                {
            "fqsen": "\\Controllers\\User\\DashboardController",
            "name": "DashboardController",
            "summary": "DashboardController\u0020\u002D\u0020Handles\u0020user\u0020dashboard",
            "url": "classes/Controllers-User-DashboardController.html"
        },                {
            "fqsen": "\\Controllers\\User\\DashboardController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "Show\u0020dashboard\u0020page",
            "url": "classes/Controllers-User-DashboardController.html#method_index"
        },                {
            "fqsen": "\\Controllers\\User\\ResourceDetailsController",
            "name": "ResourceDetailsController",
            "summary": "BaseController\u0020\u002D\u0020Base\u0020controller\u0020class\u0020with\u0020common\u0020methods\nAll\u0020controllers\u0020should\u0020extend\u0020this\u0020class",
            "url": "classes/Controllers-User-ResourceDetailsController.html"
        },                {
            "fqsen": "\\Controllers\\User\\ResourceDetailsController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "Show\u0020resource\u0020details\u0020page",
            "url": "classes/Controllers-User-ResourceDetailsController.html#method_index"
        },                {
            "fqsen": "\\Controllers\\User\\ResourceListController",
            "name": "ResourceListController",
            "summary": "BaseController\u0020\u002D\u0020Base\u0020controller\u0020class\u0020with\u0020common\u0020methods\nAll\u0020controllers\u0020should\u0020extend\u0020this\u0020class",
            "url": "classes/Controllers-User-ResourceListController.html"
        },                {
            "fqsen": "\\Controllers\\User\\ResourceListController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "Show\u0020dashboard\u0020page",
            "url": "classes/Controllers-User-ResourceListController.html#method_index"
        },                {
            "fqsen": "\\Controllers\\User\\StudentsController",
            "name": "StudentsController",
            "summary": "StudentsController\u0020\u002D\u0020Handles\u0020student\u0020data\u0020API",
            "url": "classes/Controllers-User-StudentsController.html"
        },                {
            "fqsen": "\\Controllers\\User\\StudentsController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Controllers-User-StudentsController.html#method___construct"
        },                {
            "fqsen": "\\Controllers\\User\\StudentsController\u003A\u003AgetStudents\u0028\u0029",
            "name": "getStudents",
            "summary": "Get\u0020paginated\u0020list\u0020of\u0020students",
            "url": "classes/Controllers-User-StudentsController.html#method_getStudents"
        },                {
            "fqsen": "\\Controllers\\User\\StudentsController\u003A\u003AgetStudent\u0028\u0029",
            "name": "getStudent",
            "summary": "Get\u0020student\u0020details\u0020and\u0020all\u0020attempts\u0020by\u0020ID",
            "url": "classes/Controllers-User-StudentsController.html#method_getStudent"
        },                {
            "fqsen": "\\Controllers\\User\\StudentsController\u003A\u003A\u0024studentModel",
            "name": "studentModel",
            "summary": "",
            "url": "classes/Controllers-User-StudentsController.html#property_studentModel"
        },                {
            "fqsen": "\\Code2VecService",
            "name": "Code2VecService",
            "summary": "Service\u0020pour\u0020interagir\u0020avec\u0020code2aes2vec\u0020\u0028Python\u0029\nG\u00E9n\u00E8re\u0020les\u0020vecteurs\u0020de\u0020grande\u0020dimension\u0020\u00E0\u0020partir\u0020des\u0020programmes\u0020\u00E9tudiants",
            "url": "classes/Code2VecService.html"
        },                {
            "fqsen": "\\Code2VecService\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Code2VecService.html#method___construct"
        },                {
            "fqsen": "\\Code2VecService\u003A\u003AexportDatasetToJSON\u0028\u0029",
            "name": "exportDatasetToJSON",
            "summary": "Exporte\u0020un\u0020dataset\u0020au\u0020format\u0020JSON\u0020compatible\u0020avec\u0020code2aes2vec",
            "url": "classes/Code2VecService.html#method_exportDatasetToJSON"
        },                {
            "fqsen": "\\Code2VecService\u003A\u003AexportExercisesToJSON\u0028\u0029",
            "name": "exportExercisesToJSON",
            "summary": "Exporte\u0020les\u0020exercices\u0020d\u0027un\u0020dataset\u0020au\u0020format\u0020compatible\u0020code2aes2vec",
            "url": "classes/Code2VecService.html#method_exportExercisesToJSON"
        },                {
            "fqsen": "\\Code2VecService\u003A\u003AgenerateAES\u0028\u0029",
            "name": "generateAES",
            "summary": "G\u00E9n\u00E8re\u0020les\u0020AES\u0020pour\u0020toutes\u0020les\u0020tentatives\u0020d\u0027un\u0020dataset\nMet\u0020\u00E0\u0020jour\u0020la\u0020colonne\u0020aes2\u0020dans\u0020la\u0020table\u0020attempts",
            "url": "classes/Code2VecService.html#method_generateAES"
        },                {
            "fqsen": "\\Code2VecService\u003A\u003AimportAESToDB\u0028\u0029",
            "name": "importAESToDB",
            "summary": "Importe\u0020les\u0020AES\u0020depuis\u0020le\u0020fichier\u0020JSON\u0020vers\u0020la\u0020base\u0020de\u0020donn\u00E9es",
            "url": "classes/Code2VecService.html#method_importAESToDB"
        },                {
            "fqsen": "\\Code2VecService\u003A\u003AinferVectors\u0028\u0029",
            "name": "inferVectors",
            "summary": "G\u00E9n\u00E8re\u0020les\u0020vecteurs\u0020de\u0020grande\u0020dimension\u0020\u00E0\u0020partir\u0020des\u0020AES",
            "url": "classes/Code2VecService.html#method_inferVectors"
        },                {
            "fqsen": "\\Code2VecService\u003A\u003AgetProcessingStatus\u0028\u0029",
            "name": "getProcessingStatus",
            "summary": "V\u00E9rifie\u0020l\u0027\u00E9tat\u0020du\u0020traitement",
            "url": "classes/Code2VecService.html#method_getProcessingStatus"
        },                {
            "fqsen": "\\Code2VecService\u003A\u003AprocessInBackground\u0028\u0029",
            "name": "processInBackground",
            "summary": "Lance\u0020le\u0020traitement\u0020complet\u0020en\u0020arri\u00E8re\u002Dplan",
            "url": "classes/Code2VecService.html#method_processInBackground"
        },                {
            "fqsen": "\\Code2VecService\u003A\u003A\u0024pythonPath",
            "name": "pythonPath",
            "summary": "",
            "url": "classes/Code2VecService.html#property_pythonPath"
        },                {
            "fqsen": "\\Code2VecService\u003A\u003A\u0024scriptsPath",
            "name": "scriptsPath",
            "summary": "",
            "url": "classes/Code2VecService.html#property_scriptsPath"
        },                {
            "fqsen": "\\Code2VecService\u003A\u003A\u0024dataPath",
            "name": "dataPath",
            "summary": "",
            "url": "classes/Code2VecService.html#property_dataPath"
        },                {
            "fqsen": "\\Code2VecService\u003A\u003A\u0024modelsPath",
            "name": "modelsPath",
            "summary": "",
            "url": "classes/Code2VecService.html#property_modelsPath"
        },                {
            "fqsen": "\\Database",
            "name": "Database",
            "summary": "Database\u0020class\u0020\u002D\u0020Database\u0020connection\u0020manager\nHandles\u0020PDO\u0020connection\u0020with\u0020configuration\u0020from\u0020.env\u0020file",
            "url": "classes/Database.html"
        },                {
            "fqsen": "\\Database\u003A\u003AgetConnection\u0028\u0029",
            "name": "getConnection",
            "summary": "Get\u0020PDO\u0020database\u0020connection",
            "url": "classes/Database.html#method_getConnection"
        },                {
            "fqsen": "\\Dataset",
            "name": "Dataset",
            "summary": "Mod\u00E8le\u0020pour\u0020g\u00E9rer\u0020les\u0020datasets\nUtilise\u0020la\u0020structure\u0020BD\u0020existante",
            "url": "classes/Dataset.html"
        },                {
            "fqsen": "\\Dataset\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Dataset.html#method___construct"
        },                {
            "fqsen": "\\Dataset\u003A\u003AgetByTeacher\u0028\u0029",
            "name": "getByTeacher",
            "summary": "R\u00E9cup\u00E8re\u0020tous\u0020les\u0020datasets\u0020d\u0027un\u0020enseignant",
            "url": "classes/Dataset.html#method_getByTeacher"
        },                {
            "fqsen": "\\Dataset\u003A\u003AgetById\u0028\u0029",
            "name": "getById",
            "summary": "R\u00E9cup\u00E8re\u0020un\u0020dataset\u0020par\u0020son\u0020ID",
            "url": "classes/Dataset.html#method_getById"
        },                {
            "fqsen": "\\Dataset\u003A\u003AgetAttemptsWithVectors\u0028\u0029",
            "name": "getAttemptsWithVectors",
            "summary": "R\u00E9cup\u00E8re\u0020toutes\u0020les\u0020tentatives\u0020d\u0027un\u0020dataset\u0020avec\u0020vecteurs",
            "url": "classes/Dataset.html#method_getAttemptsWithVectors"
        },                {
            "fqsen": "\\Dataset\u003A\u003AhasAccess\u0028\u0029",
            "name": "hasAccess",
            "summary": "V\u00E9rifie\u0020si\u0020l\u0027enseignant\u0020a\u0020acc\u00E8s\u0020au\u0020dataset",
            "url": "classes/Dataset.html#method_hasAccess"
        },                {
            "fqsen": "\\Dataset\u003A\u003A\u0024pdo",
            "name": "pdo",
            "summary": "",
            "url": "classes/Dataset.html#property_pdo"
        },                {
            "fqsen": "\\EmailService",
            "name": "EmailService",
            "summary": "EmailService\u0020class\u0020\u002D\u0020Email\u0020sending\u0020service\nHandles\u0020email\u0020sending\u0020with\u0020PHPMailer",
            "url": "classes/EmailService.html"
        },                {
            "fqsen": "\\EmailService\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/EmailService.html#method___construct"
        },                {
            "fqsen": "\\EmailService\u003A\u003AconfigureMail\u0028\u0029",
            "name": "configureMail",
            "summary": "Configure\u0020PHPMailer\u0020with\u0020SMTP\u0020settings",
            "url": "classes/EmailService.html#method_configureMail"
        },                {
            "fqsen": "\\EmailService\u003A\u003AsendVerificationCode\u0028\u0029",
            "name": "sendVerificationCode",
            "summary": "Send\u0020verification\u0020code\u0020email",
            "url": "classes/EmailService.html#method_sendVerificationCode"
        },                {
            "fqsen": "\\EmailService\u003A\u003AsendResetLink\u0028\u0029",
            "name": "sendResetLink",
            "summary": "Send\u0020password\u0020reset\u0020link\u0020email",
            "url": "classes/EmailService.html#method_sendResetLink"
        },                {
            "fqsen": "\\EmailService\u003A\u003A\u0024env",
            "name": "env",
            "summary": "",
            "url": "classes/EmailService.html#property_env"
        },                {
            "fqsen": "\\Exercise",
            "name": "Exercise",
            "summary": "",
            "url": "classes/Exercise.html"
        },                {
            "fqsen": "\\Exercise\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Exercise.html#method___construct"
        },                {
            "fqsen": "\\Exercise\u003A\u003Ahydrate\u0028\u0029",
            "name": "hydrate",
            "summary": "",
            "url": "classes/Exercise.html#method_hydrate"
        },                {
            "fqsen": "\\Exercise\u003A\u003AgetExercisesByResourceId\u0028\u0029",
            "name": "getExercisesByResourceId",
            "summary": "",
            "url": "classes/Exercise.html#method_getExercisesByResourceId"
        },                {
            "fqsen": "\\Exercise\u003A\u003AgetExerciseById\u0028\u0029",
            "name": "getExerciseById",
            "summary": "",
            "url": "classes/Exercise.html#method_getExerciseById"
        },                {
            "fqsen": "\\Exercise\u003A\u003AgetByDataset\u0028\u0029",
            "name": "getByDataset",
            "summary": "R\u00E9cup\u00E8re\u0020tous\u0020les\u0020exercices\u0020d\u0027un\u0020dataset",
            "url": "classes/Exercise.html#method_getByDataset"
        },                {
            "fqsen": "\\Exercise\u003A\u003AgetById\u0028\u0029",
            "name": "getById",
            "summary": "R\u00E9cup\u00E8re\u0020un\u0020exercice\u0020par\u0020son\u0020ID",
            "url": "classes/Exercise.html#method_getById"
        },                {
            "fqsen": "\\Exercise\u003A\u003AgetTestCases\u0028\u0029",
            "name": "getTestCases",
            "summary": "R\u00E9cup\u00E8re\u0020les\u0020test\u0020cases\u0020d\u0027un\u0020exercice",
            "url": "classes/Exercise.html#method_getTestCases"
        },                {
            "fqsen": "\\Exercise\u003A\u003A\u0024db",
            "name": "db",
            "summary": "",
            "url": "classes/Exercise.html#property_db"
        },                {
            "fqsen": "\\Exercise\u003A\u003A\u0024exercise_id",
            "name": "exercise_id",
            "summary": "",
            "url": "classes/Exercise.html#property_exercise_id"
        },                {
            "fqsen": "\\Exercise\u003A\u003A\u0024resource_id",
            "name": "resource_id",
            "summary": "",
            "url": "classes/Exercise.html#property_resource_id"
        },                {
            "fqsen": "\\Exercise\u003A\u003A\u0024exo_name",
            "name": "exo_name",
            "summary": "",
            "url": "classes/Exercise.html#property_exo_name"
        },                {
            "fqsen": "\\Exercise\u003A\u003A\u0024funcname",
            "name": "funcname",
            "summary": "",
            "url": "classes/Exercise.html#property_funcname"
        },                {
            "fqsen": "\\Exercise\u003A\u003A\u0024solution",
            "name": "solution",
            "summary": "",
            "url": "classes/Exercise.html#property_solution"
        },                {
            "fqsen": "\\Exercise\u003A\u003A\u0024description",
            "name": "description",
            "summary": "",
            "url": "classes/Exercise.html#property_description"
        },                {
            "fqsen": "\\Exercise\u003A\u003A\u0024difficulte",
            "name": "difficulte",
            "summary": "",
            "url": "classes/Exercise.html#property_difficulte"
        },                {
            "fqsen": "\\Exercise\u003A\u003A\u0024date_creation",
            "name": "date_creation",
            "summary": "",
            "url": "classes/Exercise.html#property_date_creation"
        },                {
            "fqsen": "\\PendingRegistration",
            "name": "PendingRegistration",
            "summary": "PendingRegistration\u0020Model\u0020\u002D\u0020CRUD\u0020operations\u0020for\u0020pending\u0020registrations\u0020with\u0020PDO",
            "url": "classes/PendingRegistration.html"
        },                {
            "fqsen": "\\PendingRegistration\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/PendingRegistration.html#method___construct"
        },                {
            "fqsen": "\\PendingRegistration\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "CREATE\u0020\u002D\u0020Create\u0020a\u0020new\u0020pending\u0020registration",
            "url": "classes/PendingRegistration.html#method_create"
        },                {
            "fqsen": "\\PendingRegistration\u003A\u003AfindByEmail\u0028\u0029",
            "name": "findByEmail",
            "summary": "READ\u0020\u002D\u0020Find\u0020a\u0020pending\u0020registration\u0020by\u0020email",
            "url": "classes/PendingRegistration.html#method_findByEmail"
        },                {
            "fqsen": "\\PendingRegistration\u003A\u003AemailExists\u0028\u0029",
            "name": "emailExists",
            "summary": "READ\u0020\u002D\u0020Check\u0020if\u0020an\u0020email\u0020exists\u0020in\u0020pending\u0020registrations",
            "url": "classes/PendingRegistration.html#method_emailExists"
        },                {
            "fqsen": "\\PendingRegistration\u003A\u003AupdateCode\u0028\u0029",
            "name": "updateCode",
            "summary": "UPDATE\u0020\u002D\u0020Update\u0020verification\u0020code",
            "url": "classes/PendingRegistration.html#method_updateCode"
        },                {
            "fqsen": "\\PendingRegistration\u003A\u003Adelete\u0028\u0029",
            "name": "delete",
            "summary": "DELETE\u0020\u002D\u0020Delete\u0020a\u0020pending\u0020registration\u0020by\u0020email",
            "url": "classes/PendingRegistration.html#method_delete"
        },                {
            "fqsen": "\\PendingRegistration\u003A\u003AdeleteExpired\u0028\u0029",
            "name": "deleteExpired",
            "summary": "DELETE\u0020\u002D\u0020Delete\u0020expired\u0020pending\u0020registrations\u0020\u0028older\u0020than\u002015\u0020minutes\u0029",
            "url": "classes/PendingRegistration.html#method_deleteExpired"
        },                {
            "fqsen": "\\PendingRegistration\u003A\u003AverifyCode\u0028\u0029",
            "name": "verifyCode",
            "summary": "Verify\u0020verification\u0020code",
            "url": "classes/PendingRegistration.html#method_verifyCode"
        },                {
            "fqsen": "\\PendingRegistration\u003A\u003A\u0024pdo",
            "name": "pdo",
            "summary": "",
            "url": "classes/PendingRegistration.html#property_pdo"
        },                {
            "fqsen": "\\Resource",
            "name": "Resource",
            "summary": "",
            "url": "classes/Resource.html"
        },                {
            "fqsen": "\\Resource\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Resource.html#method___construct"
        },                {
            "fqsen": "\\Resource\u003A\u003Ahydrate\u0028\u0029",
            "name": "hydrate",
            "summary": "",
            "url": "classes/Resource.html#method_hydrate"
        },                {
            "fqsen": "\\Resource\u003A\u003AgetAllAccessibleResources\u0028\u0029",
            "name": "getAllAccessibleResources",
            "summary": "",
            "url": "classes/Resource.html#method_getAllAccessibleResources"
        },                {
            "fqsen": "\\Resource\u003A\u003AgetResourceById\u0028\u0029",
            "name": "getResourceById",
            "summary": "",
            "url": "classes/Resource.html#method_getResourceById"
        },                {
            "fqsen": "\\Resource\u003A\u003A\u0024db",
            "name": "db",
            "summary": "",
            "url": "classes/Resource.html#property_db"
        },                {
            "fqsen": "\\Resource\u003A\u003A\u0024resource_id",
            "name": "resource_id",
            "summary": "",
            "url": "classes/Resource.html#property_resource_id"
        },                {
            "fqsen": "\\Resource\u003A\u003A\u0024owner_user_id",
            "name": "owner_user_id",
            "summary": "",
            "url": "classes/Resource.html#property_owner_user_id"
        },                {
            "fqsen": "\\Resource\u003A\u003A\u0024resource_name",
            "name": "resource_name",
            "summary": "",
            "url": "classes/Resource.html#property_resource_name"
        },                {
            "fqsen": "\\Resource\u003A\u003A\u0024description",
            "name": "description",
            "summary": "",
            "url": "classes/Resource.html#property_description"
        },                {
            "fqsen": "\\Resource\u003A\u003A\u0024image_path",
            "name": "image_path",
            "summary": "",
            "url": "classes/Resource.html#property_image_path"
        },                {
            "fqsen": "\\Resource\u003A\u003A\u0024date_creation",
            "name": "date_creation",
            "summary": "",
            "url": "classes/Resource.html#property_date_creation"
        },                {
            "fqsen": "\\Resource\u003A\u003A\u0024owner_firstname",
            "name": "owner_firstname",
            "summary": "",
            "url": "classes/Resource.html#property_owner_firstname"
        },                {
            "fqsen": "\\Resource\u003A\u003A\u0024owner_lastname",
            "name": "owner_lastname",
            "summary": "",
            "url": "classes/Resource.html#property_owner_lastname"
        },                {
            "fqsen": "\\Resource\u003A\u003A\u0024access_type",
            "name": "access_type",
            "summary": "",
            "url": "classes/Resource.html#property_access_type"
        },                {
            "fqsen": "\\Student",
            "name": "Student",
            "summary": "Student\u0020Model\u0020\u002D\u0020Handles\u0020student\u0020data\u0020from\u0020database",
            "url": "classes/Student.html"
        },                {
            "fqsen": "\\Student\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Student.html#method___construct"
        },                {
            "fqsen": "\\Student\u003A\u003AisInitialized\u0028\u0029",
            "name": "isInitialized",
            "summary": "Check\u0020if\u0020the\u0020model\u0020is\u0020properly\u0020initialized",
            "url": "classes/Student.html#method_isInitialized"
        },                {
            "fqsen": "\\Student\u003A\u003AgetInitError\u0028\u0029",
            "name": "getInitError",
            "summary": "Get\u0020initialization\u0020error\u0020if\u0020any",
            "url": "classes/Student.html#method_getInitError"
        },                {
            "fqsen": "\\Student\u003A\u003AgetAllStudents\u0028\u0029",
            "name": "getAllStudents",
            "summary": "Get\u0020all\u0020students\u0020for\u0020a\u0020specific\u0020resource",
            "url": "classes/Student.html#method_getAllStudents"
        },                {
            "fqsen": "\\Student\u003A\u003AgetPaginatedStudents\u0028\u0029",
            "name": "getPaginatedStudents",
            "summary": "Get\u0020paginated\u0020students\u0020for\u0020a\u0020specific\u0020resource",
            "url": "classes/Student.html#method_getPaginatedStudents"
        },                {
            "fqsen": "\\Student\u003A\u003AgetStudentAttempts\u0028\u0029",
            "name": "getStudentAttempts",
            "summary": "Get\u0020all\u0020attempts\u0020for\u0020a\u0020specific\u0020student",
            "url": "classes/Student.html#method_getStudentAttempts"
        },                {
            "fqsen": "\\Student\u003A\u003AgetExerciseTestCases\u0028\u0029",
            "name": "getExerciseTestCases",
            "summary": "Get\u0020test\u0020cases\u0020for\u0020a\u0020specific\u0020exercise",
            "url": "classes/Student.html#method_getExerciseTestCases"
        },                {
            "fqsen": "\\Student\u003A\u003AgetStudentById\u0028\u0029",
            "name": "getStudentById",
            "summary": "Get\u0020student\u0020by\u0020ID",
            "url": "classes/Student.html#method_getStudentById"
        },                {
            "fqsen": "\\Student\u003A\u003AgetStudentStats\u0028\u0029",
            "name": "getStudentStats",
            "summary": "Get\u0020statistics\u0020for\u0020a\u0020student",
            "url": "classes/Student.html#method_getStudentStats"
        },                {
            "fqsen": "\\Student\u003A\u003AgetStudentByIdentifier\u0028\u0029",
            "name": "getStudentByIdentifier",
            "summary": "Get\u0020student\u0020by\u0020identifier\u0020\u0028student_identifier\u0029",
            "url": "classes/Student.html#method_getStudentByIdentifier"
        },                {
            "fqsen": "\\Student\u003A\u003A\u0024db",
            "name": "db",
            "summary": "",
            "url": "classes/Student.html#property_db"
        },                {
            "fqsen": "\\Student\u003A\u003A\u0024initError",
            "name": "initError",
            "summary": "",
            "url": "classes/Student.html#property_initError"
        },                {
            "fqsen": "\\User",
            "name": "User",
            "summary": "User\u0020Model\u0020\u002D\u0020CRUD\u0020operations\u0020for\u0020users\u0020with\u0020PDO",
            "url": "classes/User.html"
        },                {
            "fqsen": "\\User\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/User.html#method___construct"
        },                {
            "fqsen": "\\User\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "CREATE\u0020\u002D\u0020Create\u0020a\u0020new\u0020user",
            "url": "classes/User.html#method_create"
        },                {
            "fqsen": "\\User\u003A\u003AfindByEmail\u0028\u0029",
            "name": "findByEmail",
            "summary": "READ\u0020\u002D\u0020Find\u0020a\u0020user\u0020by\u0020email",
            "url": "classes/User.html#method_findByEmail"
        },                {
            "fqsen": "\\User\u003A\u003AfindById\u0028\u0029",
            "name": "findById",
            "summary": "READ\u0020\u002D\u0020Find\u0020a\u0020user\u0020by\u0020ID",
            "url": "classes/User.html#method_findById"
        },                {
            "fqsen": "\\User\u003A\u003AemailExists\u0028\u0029",
            "name": "emailExists",
            "summary": "READ\u0020\u002D\u0020Check\u0020if\u0020an\u0020email\u0020exists",
            "url": "classes/User.html#method_emailExists"
        },                {
            "fqsen": "\\User\u003A\u003AfindByResetToken\u0028\u0029",
            "name": "findByResetToken",
            "summary": "READ\u0020\u002D\u0020Find\u0020a\u0020user\u0020by\u0020reset\u0020token",
            "url": "classes/User.html#method_findByResetToken"
        },                {
            "fqsen": "\\User\u003A\u003AupdatePassword\u0028\u0029",
            "name": "updatePassword",
            "summary": "UPDATE\u0020\u002D\u0020Update\u0020user\u0027s\u0020password",
            "url": "classes/User.html#method_updatePassword"
        },                {
            "fqsen": "\\User\u003A\u003AsetResetToken\u0028\u0029",
            "name": "setResetToken",
            "summary": "UPDATE\u0020\u002D\u0020Set\u0020password\u0020reset\u0020token",
            "url": "classes/User.html#method_setResetToken"
        },                {
            "fqsen": "\\User\u003A\u003AclearResetToken\u0028\u0029",
            "name": "clearResetToken",
            "summary": "UPDATE\u0020\u002D\u0020Clear\u0020password\u0020reset\u0020token",
            "url": "classes/User.html#method_clearResetToken"
        },                {
            "fqsen": "\\User\u003A\u003Aupdate\u0028\u0029",
            "name": "update",
            "summary": "UPDATE\u0020\u002D\u0020Update\u0020user\u0020information",
            "url": "classes/User.html#method_update"
        },                {
            "fqsen": "\\User\u003A\u003Adelete\u0028\u0029",
            "name": "delete",
            "summary": "DELETE\u0020\u002D\u0020Delete\u0020a\u0020user",
            "url": "classes/User.html#method_delete"
        },                {
            "fqsen": "\\User\u003A\u003AverifyCredentials\u0028\u0029",
            "name": "verifyCredentials",
            "summary": "Verify\u0020user\u0020credentials\u0020for\u0020login",
            "url": "classes/User.html#method_verifyCredentials"
        },                {
            "fqsen": "\\User\u003A\u003A\u0024pdo",
            "name": "pdo",
            "summary": "",
            "url": "classes/User.html#property_pdo"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Controllers\\Analysis",
            "name": "Analysis",
            "summary": "",
            "url": "namespaces/controllers-analysis.html"
        },                {
            "fqsen": "\\Controllers",
            "name": "Controllers",
            "summary": "",
            "url": "namespaces/controllers.html"
        },                {
            "fqsen": "\\Controllers\\Auth",
            "name": "Auth",
            "summary": "",
            "url": "namespaces/controllers-auth.html"
        },                {
            "fqsen": "\\Controllers\\User",
            "name": "User",
            "summary": "",
            "url": "namespaces/controllers-user.html"
        }            ]
);
